//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.04 at 07:04:12 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://www.siged.sep.gob.mx/titulos/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package mx.ciatej.titulos.ws;
