//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.04 at 07:04:12 PM CST 
//


package mx.ciatej.titulos.ws;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "firmaResponsables",
    "institucion",
    "carrera",
    "profesionista",
    "expedicion",
    "antecedente",
    "autenticacion"
})
@XmlRootElement(name = "TituloElectronico")
public class TituloElectronico {

    @XmlElement(name = "FirmaResponsables", required = true)
    protected TituloElectronico.FirmaResponsables firmaResponsables;
    @XmlElement(name = "Institucion", required = true)
    protected TituloElectronico.Institucion institucion;
    @XmlElement(name = "Carrera", required = true)
    protected TituloElectronico.Carrera carrera;
    @XmlElement(name = "Profesionista", required = true)
    protected TituloElectronico.Profesionista profesionista;
    @XmlElement(name = "Expedicion", required = true)
    protected TituloElectronico.Expedicion expedicion;
    @XmlElement(name = "Antecedente", required = true)
    protected TituloElectronico.Antecedente antecedente;
    @XmlElement(name = "Autenticacion")
    protected TituloElectronico.Autenticacion autenticacion;
    @XmlAttribute(name = "version", required = true)
    protected String version;
    @XmlAttribute(name = "folioControl", required = true)
    protected String folioControl;

    /**
     * Gets the value of the firmaResponsables property.
     * 
     * @return
     *     possible object is
     *     {@link TituloElectronico.FirmaResponsables }
     *     
     */
    public TituloElectronico.FirmaResponsables getFirmaResponsables() {
        return firmaResponsables;
    }

    /**
     * Sets the value of the firmaResponsables property.
     * 
     * @param value
     *     allowed object is
     *     {@link TituloElectronico.FirmaResponsables }
     *     
     */
    public void setFirmaResponsables(TituloElectronico.FirmaResponsables value) {
        this.firmaResponsables = value;
    }

    /**
     * Gets the value of the institucion property.
     * 
     * @return
     *     possible object is
     *     {@link TituloElectronico.Institucion }
     *     
     */
    public TituloElectronico.Institucion getInstitucion() {
        return institucion;
    }

    /**
     * Sets the value of the institucion property.
     * 
     * @param value
     *     allowed object is
     *     {@link TituloElectronico.Institucion }
     *     
     */
    public void setInstitucion(TituloElectronico.Institucion value) {
        this.institucion = value;
    }

    /**
     * Gets the value of the carrera property.
     * 
     * @return
     *     possible object is
     *     {@link TituloElectronico.Carrera }
     *     
     */
    public TituloElectronico.Carrera getCarrera() {
        return carrera;
    }

    /**
     * Sets the value of the carrera property.
     * 
     * @param value
     *     allowed object is
     *     {@link TituloElectronico.Carrera }
     *     
     */
    public void setCarrera(TituloElectronico.Carrera value) {
        this.carrera = value;
    }

    /**
     * Gets the value of the profesionista property.
     * 
     * @return
     *     possible object is
     *     {@link TituloElectronico.Profesionista }
     *     
     */
    public TituloElectronico.Profesionista getProfesionista() {
        return profesionista;
    }

    /**
     * Sets the value of the profesionista property.
     * 
     * @param value
     *     allowed object is
     *     {@link TituloElectronico.Profesionista }
     *     
     */
    public void setProfesionista(TituloElectronico.Profesionista value) {
        this.profesionista = value;
    }

    /**
     * Gets the value of the expedicion property.
     * 
     * @return
     *     possible object is
     *     {@link TituloElectronico.Expedicion }
     *     
     */
    public TituloElectronico.Expedicion getExpedicion() {
        return expedicion;
    }

    /**
     * Sets the value of the expedicion property.
     * 
     * @param value
     *     allowed object is
     *     {@link TituloElectronico.Expedicion }
     *     
     */
    public void setExpedicion(TituloElectronico.Expedicion value) {
        this.expedicion = value;
    }

    /**
     * Gets the value of the antecedente property.
     * 
     * @return
     *     possible object is
     *     {@link TituloElectronico.Antecedente }
     *     
     */
    public TituloElectronico.Antecedente getAntecedente() {
        return antecedente;
    }

    /**
     * Sets the value of the antecedente property.
     * 
     * @param value
     *     allowed object is
     *     {@link TituloElectronico.Antecedente }
     *     
     */
    public void setAntecedente(TituloElectronico.Antecedente value) {
        this.antecedente = value;
    }

    /**
     * Gets the value of the autenticacion property.
     * 
     * @return
     *     possible object is
     *     {@link TituloElectronico.Autenticacion }
     *     
     */
    public TituloElectronico.Autenticacion getAutenticacion() {
        return autenticacion;
    }

    /**
     * Sets the value of the autenticacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link TituloElectronico.Autenticacion }
     *     
     */
    public void setAutenticacion(TituloElectronico.Autenticacion value) {
        this.autenticacion = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        if (version == null) {
            return "1.0";
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the folioControl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFolioControl() {
        return folioControl;
    }

    /**
     * Sets the value of the folioControl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFolioControl(String value) {
        this.folioControl = value;
    }


        @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Antecedente {

        @XmlAttribute(name = "institucionProcedencia", required = true)
        protected String institucionProcedencia;
        @XmlAttribute(name = "idTipoEstudioAntecedente", required = true)
        protected BigInteger idTipoEstudioAntecedente;
        @XmlAttribute(name = "tipoEstudioAntecedente", required = true)
        protected String tipoEstudioAntecedente;
        @XmlAttribute(name = "idEntidadFederativa", required = true)
        protected String idEntidadFederativa;
        @XmlAttribute(name = "entidadFederativa")
        protected String entidadFederativa;
        @XmlAttribute(name = "fechaInicio")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar fechaInicio;
        @XmlAttribute(name = "fechaTerminacion", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar fechaTerminacion;
        @XmlAttribute(name = "noCedula")
        protected String noCedula;

        /**
         * Gets the value of the institucionProcedencia property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInstitucionProcedencia() {
            return institucionProcedencia;
        }

        /**
         * Sets the value of the institucionProcedencia property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInstitucionProcedencia(String value) {
            this.institucionProcedencia = value;
        }

        /**
         * Gets the value of the idTipoEstudioAntecedente property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getIdTipoEstudioAntecedente() {
            return idTipoEstudioAntecedente;
        }

        /**
         * Sets the value of the idTipoEstudioAntecedente property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setIdTipoEstudioAntecedente(BigInteger value) {
            this.idTipoEstudioAntecedente = value;
        }

        /**
         * Gets the value of the tipoEstudioAntecedente property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTipoEstudioAntecedente() {
            return tipoEstudioAntecedente;
        }

        /**
         * Sets the value of the tipoEstudioAntecedente property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTipoEstudioAntecedente(String value) {
            this.tipoEstudioAntecedente = value;
        }

        /**
         * Gets the value of the idEntidadFederativa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIdEntidadFederativa() {
            return idEntidadFederativa;
        }

        /**
         * Sets the value of the idEntidadFederativa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIdEntidadFederativa(String value) {
            this.idEntidadFederativa = value;
        }

        /**
         * Gets the value of the entidadFederativa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEntidadFederativa() {
            return entidadFederativa;
        }

        /**
         * Sets the value of the entidadFederativa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEntidadFederativa(String value) {
            this.entidadFederativa = value;
        }

        /**
         * Gets the value of the fechaInicio property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getFechaInicio() {
            return fechaInicio;
        }

        /**
         * Sets the value of the fechaInicio property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setFechaInicio(XMLGregorianCalendar value) {
            this.fechaInicio = value;
        }

        /**
         * Gets the value of the fechaTerminacion property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getFechaTerminacion() {
            return fechaTerminacion;
        }

        /**
         * Sets the value of the fechaTerminacion property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setFechaTerminacion(XMLGregorianCalendar value) {
            this.fechaTerminacion = value;
        }

        /**
         * Gets the value of the noCedula property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNoCedula() {
            return noCedula;
        }

        /**
         * Sets the value of the noCedula property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNoCedula(String value) {
            this.noCedula = value;
        }

    }


   
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "any"
    })
    public static class Autenticacion {

        @XmlAnyElement(lax = true)
        protected Object any;

        /**
         * Gets the value of the any property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getAny() {
            return any;
        }

        /**
         * Sets the value of the any property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setAny(Object value) {
            this.any = value;
        }

    }


    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Carrera {

        @XmlAttribute(name = "cveCarrera", required = true)
        protected String cveCarrera;
        @XmlAttribute(name = "nombreCarrera", required = true)
        protected String nombreCarrera;
        @XmlAttribute(name = "fechaInicio")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar fechaInicio;
        @XmlAttribute(name = "fechaTerminacion", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar fechaTerminacion;
        @XmlAttribute(name = "idAutorizacionReconocimiento", required = true)
        protected BigInteger idAutorizacionReconocimiento;
        @XmlAttribute(name = "autorizacionReconocimiento", required = true)
        protected String autorizacionReconocimiento;
        @XmlAttribute(name = "numeroRvoe")
        protected String numeroRvoe;

        /**
         * Gets the value of the cveCarrera property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCveCarrera() {
            return cveCarrera;
        }

        /**
         * Sets the value of the cveCarrera property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCveCarrera(String value) {
            this.cveCarrera = value;
        }

        /**
         * Gets the value of the nombreCarrera property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNombreCarrera() {
            return nombreCarrera;
        }

        /**
         * Sets the value of the nombreCarrera property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNombreCarrera(String value) {
            this.nombreCarrera = value;
        }

        /**
         * Gets the value of the fechaInicio property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getFechaInicio() {
            return fechaInicio;
        }

        /**
         * Sets the value of the fechaInicio property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setFechaInicio(XMLGregorianCalendar value) {
            this.fechaInicio = value;
        }

        /**
         * Gets the value of the fechaTerminacion property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getFechaTerminacion() {
            return fechaTerminacion;
        }

        /**
         * Sets the value of the fechaTerminacion property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setFechaTerminacion(XMLGregorianCalendar value) {
            this.fechaTerminacion = value;
        }

        /**
         * Gets the value of the idAutorizacionReconocimiento property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getIdAutorizacionReconocimiento() {
            return idAutorizacionReconocimiento;
        }

        /**
         * Sets the value of the idAutorizacionReconocimiento property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setIdAutorizacionReconocimiento(BigInteger value) {
            this.idAutorizacionReconocimiento = value;
        }

        /**
         * Gets the value of the autorizacionReconocimiento property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAutorizacionReconocimiento() {
            return autorizacionReconocimiento;
        }

        /**
         * Sets the value of the autorizacionReconocimiento property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAutorizacionReconocimiento(String value) {
            this.autorizacionReconocimiento = value;
        }

        /**
         * Gets the value of the numeroRvoe property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNumeroRvoe() {
            return numeroRvoe;
        }

        /**
         * Sets the value of the numeroRvoe property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNumeroRvoe(String value) {
            this.numeroRvoe = value;
        }

    }


   
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Expedicion {

        @XmlAttribute(name = "fechaExpedicion", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar fechaExpedicion;
        @XmlAttribute(name = "idModalidadTitulacion", required = true)
        protected BigInteger idModalidadTitulacion;
        @XmlAttribute(name = "modalidadTitulacion", required = true)
        protected String modalidadTitulacion;
        @XmlAttribute(name = "fechaExamenProfesional")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar fechaExamenProfesional;
        @XmlAttribute(name = "fechaExencionExamenProfesional")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar fechaExencionExamenProfesional;
        @XmlAttribute(name = "cumplioServicioSocial", required = true)
        protected BigInteger cumplioServicioSocial;
        @XmlAttribute(name = "idFundamentoLegalServicioSocial", required = true)
        protected BigInteger idFundamentoLegalServicioSocial;
        @XmlAttribute(name = "fundamentoLegalServicioSocial", required = true)
        protected String fundamentoLegalServicioSocial;
        @XmlAttribute(name = "idEntidadFederativa", required = true)
        protected String idEntidadFederativa;
        @XmlAttribute(name = "entidadFederativa", required = true)
        protected String entidadFederativa;

        /**
         * Gets the value of the fechaExpedicion property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getFechaExpedicion() {
            return fechaExpedicion;
        }

        /**
         * Sets the value of the fechaExpedicion property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setFechaExpedicion(XMLGregorianCalendar value) {
            this.fechaExpedicion = value;
        }

        /**
         * Gets the value of the idModalidadTitulacion property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getIdModalidadTitulacion() {
            return idModalidadTitulacion;
        }

        /**
         * Sets the value of the idModalidadTitulacion property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setIdModalidadTitulacion(BigInteger value) {
            this.idModalidadTitulacion = value;
        }

        /**
         * Gets the value of the modalidadTitulacion property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getModalidadTitulacion() {
            return modalidadTitulacion;
        }

        /**
         * Sets the value of the modalidadTitulacion property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setModalidadTitulacion(String value) {
            this.modalidadTitulacion = value;
        }

        /**
         * Gets the value of the fechaExamenProfesional property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getFechaExamenProfesional() {
            return fechaExamenProfesional;
        }

        /**
         * Sets the value of the fechaExamenProfesional property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setFechaExamenProfesional(XMLGregorianCalendar value) {
            this.fechaExamenProfesional = value;
        }

        /**
         * Gets the value of the fechaExencionExamenProfesional property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getFechaExencionExamenProfesional() {
            return fechaExencionExamenProfesional;
        }

        /**
         * Sets the value of the fechaExencionExamenProfesional property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setFechaExencionExamenProfesional(XMLGregorianCalendar value) {
            this.fechaExencionExamenProfesional = value;
        }

        /**
         * Gets the value of the cumplioServicioSocial property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getCumplioServicioSocial() {
            return cumplioServicioSocial;
        }

        /**
         * Sets the value of the cumplioServicioSocial property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setCumplioServicioSocial(BigInteger value) {
            this.cumplioServicioSocial = value;
        }

        /**
         * Gets the value of the idFundamentoLegalServicioSocial property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getIdFundamentoLegalServicioSocial() {
            return idFundamentoLegalServicioSocial;
        }

        /**
         * Sets the value of the idFundamentoLegalServicioSocial property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setIdFundamentoLegalServicioSocial(BigInteger value) {
            this.idFundamentoLegalServicioSocial = value;
        }

        /**
         * Gets the value of the fundamentoLegalServicioSocial property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFundamentoLegalServicioSocial() {
            return fundamentoLegalServicioSocial;
        }

        /**
         * Sets the value of the fundamentoLegalServicioSocial property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFundamentoLegalServicioSocial(String value) {
            this.fundamentoLegalServicioSocial = value;
        }

        /**
         * Gets the value of the idEntidadFederativa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIdEntidadFederativa() {
            return idEntidadFederativa;
        }

        /**
         * Sets the value of the idEntidadFederativa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIdEntidadFederativa(String value) {
            this.idEntidadFederativa = value;
        }

        /**
         * Gets the value of the entidadFederativa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEntidadFederativa() {
            return entidadFederativa;
        }

        /**
         * Sets the value of the entidadFederativa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEntidadFederativa(String value) {
            this.entidadFederativa = value;
        }

    }


    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "firmaResponsable"
    })
    public static class FirmaResponsables {

        @XmlElement(name = "FirmaResponsable", required = true)
        protected List<TituloElectronico.FirmaResponsables.FirmaResponsable> firmaResponsable;

        public List<TituloElectronico.FirmaResponsables.FirmaResponsable> getFirmaResponsable() {
            if (firmaResponsable == null) {
                firmaResponsable = new ArrayList<TituloElectronico.FirmaResponsables.FirmaResponsable>();
            }
            return this.firmaResponsable;
        }

        public  void setFirmaResponsable(TituloElectronico.FirmaResponsables.FirmaResponsable res){
            if (firmaResponsable == null){
                getFirmaResponsable() ;
            }
                
            firmaResponsable.add(res);
        }

        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class FirmaResponsable {

            @XmlAttribute(name = "nombre", required = true)
            protected String nombre;
            @XmlAttribute(name = "primerApellido", required = true)
            protected String primerApellido;
            @XmlAttribute(name = "segundoApellido")
            protected String segundoApellido;
            @XmlAttribute(name = "curp", required = true)
            protected String curp;
            @XmlAttribute(name = "idCargo", required = true)
            protected BigInteger idCargo;
            @XmlAttribute(name = "cargo", required = true)
            protected String cargo;
            @XmlAttribute(name = "abrTitulo")
            protected String abrTitulo;
            @XmlAttribute(name = "sello", required = true)
            protected String sello;
            @XmlAttribute(name = "certificadoResponsable", required = true)
            protected String certificadoResponsable;
            @XmlAttribute(name = "noCertificadoResponsable", required = true)
            protected String noCertificadoResponsable;

            /**
             * Gets the value of the nombre property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNombre() {
                return nombre;
            }

            /**
             * Sets the value of the nombre property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNombre(String value) {
                this.nombre = value;
            }

            /**
             * Gets the value of the primerApellido property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPrimerApellido() {
                return primerApellido;
            }

            /**
             * Sets the value of the primerApellido property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPrimerApellido(String value) {
                this.primerApellido = value;
            }

            /**
             * Gets the value of the segundoApellido property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSegundoApellido() {
                return segundoApellido;
            }

            /**
             * Sets the value of the segundoApellido property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSegundoApellido(String value) {
                this.segundoApellido = value;
            }

            /**
             * Gets the value of the curp property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCurp() {
                return curp;
            }

            /**
             * Sets the value of the curp property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCurp(String value) {
                this.curp = value;
            }

            /**
             * Gets the value of the idCargo property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getIdCargo() {
                return idCargo;
            }

            /**
             * Sets the value of the idCargo property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setIdCargo(BigInteger value) {
                this.idCargo = value;
            }

            /**
             * Gets the value of the cargo property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCargo() {
                return cargo;
            }

            /**
             * Sets the value of the cargo property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCargo(String value) {
                this.cargo = value;
            }

            /**
             * Gets the value of the abrTitulo property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAbrTitulo() {
                return abrTitulo;
            }

            /**
             * Sets the value of the abrTitulo property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAbrTitulo(String value) {
                this.abrTitulo = value;
            }

            /**
             * Gets the value of the sello property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSello() {
                return sello;
            }

            /**
             * Sets the value of the sello property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSello(String value) {
                this.sello = value;
            }

            /**
             * Gets the value of the certificadoResponsable property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCertificadoResponsable() {
                return certificadoResponsable;
            }

            /**
             * Sets the value of the certificadoResponsable property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCertificadoResponsable(String value) {
                this.certificadoResponsable = value;
            }

            /**
             * Gets the value of the noCertificadoResponsable property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNoCertificadoResponsable() {
                return noCertificadoResponsable;
            }

            /**
             * Sets the value of the noCertificadoResponsable property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNoCertificadoResponsable(String value) {
                this.noCertificadoResponsable = value;
            }

        }

    }


    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Institucion {

        @XmlAttribute(name = "cveInstitucion", required = true)
        protected String cveInstitucion;
        @XmlAttribute(name = "nombreInstitucion", required = true)
        protected String nombreInstitucion;

        /**
         * Gets the value of the cveInstitucion property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCveInstitucion() {
            return cveInstitucion;
        }

        /**
         * Sets the value of the cveInstitucion property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCveInstitucion(String value) {
            this.cveInstitucion = value;
        }

        /**
         * Gets the value of the nombreInstitucion property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNombreInstitucion() {
            return nombreInstitucion;
        }

        /**
         * Sets the value of the nombreInstitucion property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNombreInstitucion(String value) {
            this.nombreInstitucion = value;
        }

    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Profesionista {

        @XmlAttribute(name = "curp", required = true)
        protected String curp;
        @XmlAttribute(name = "nombre", required = true)
        protected String nombre;
        @XmlAttribute(name = "primerApellido", required = true)
        protected String primerApellido;
        @XmlAttribute(name = "segundoApellido")
        protected String segundoApellido;
        @XmlAttribute(name = "correoElectronico", required = true)
        protected String correoElectronico;

        /**
         * Gets the value of the curp property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCurp() {
            return curp;
        }

        /**
         * Sets the value of the curp property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCurp(String value) {
            this.curp = value;
        }

        /**
         * Gets the value of the nombre property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNombre() {
            return nombre;
        }

        /**
         * Sets the value of the nombre property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNombre(String value) {
            this.nombre = value;
        }

        /**
         * Gets the value of the primerApellido property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrimerApellido() {
            return primerApellido;
        }

        /**
         * Sets the value of the primerApellido property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrimerApellido(String value) {
            this.primerApellido = value;
        }

        /**
         * Gets the value of the segundoApellido property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSegundoApellido() {
            return segundoApellido;
        }

        /**
         * Sets the value of the segundoApellido property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSegundoApellido(String value) {
            this.segundoApellido = value;
        }

        /**
         * Gets the value of the correoElectronico property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCorreoElectronico() {
            return correoElectronico;
        }

        /**
         * Sets the value of the correoElectronico property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCorreoElectronico(String value) {
            this.correoElectronico = value;
        }

    }

}
