package mx.sep.mec.web.ws.schemas;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2022-08-03T16:03:27.207-05:00
 * Generated source version: 3.2.7
 *
 */
@WebServiceClient(name = "TitulosPortTypeService",
                  wsdlLocation = "file:/home/etitulos/etitulos/src/main/resources/wsdl/TituloElectronicosPROD.wsdl",
                  targetNamespace = "http://ws.web.mec.sep.mx/schemas")
public class TitulosPortTypeService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.web.mec.sep.mx/schemas", "TitulosPortTypeService");
    public final static QName TitulosPortTypeSoap11 = new QName("http://ws.web.mec.sep.mx/schemas", "TitulosPortTypeSoap11");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/etitulos/etitulos/src/main/resources/wsdl/TituloElectronicosPROD.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TitulosPortTypeService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/home/etitulos/etitulos/src/main/resources/wsdl/TituloElectronicosPROD.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TitulosPortTypeService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TitulosPortTypeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TitulosPortTypeService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public TitulosPortTypeService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public TitulosPortTypeService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public TitulosPortTypeService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns TitulosPortType
     */
    @WebEndpoint(name = "TitulosPortTypeSoap11")
    public TitulosPortType getTitulosPortTypeSoap11() {
        return super.getPort(TitulosPortTypeSoap11, TitulosPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TitulosPortType
     */
    @WebEndpoint(name = "TitulosPortTypeSoap11")
    public TitulosPortType getTitulosPortTypeSoap11(WebServiceFeature... features) {
        return super.getPort(TitulosPortTypeSoap11, TitulosPortType.class, features);
    }

}
